# config/__init__.py

from .settings import (
    PROJECT_ROOT,
    DOCUMENTS_FOLDER,
    INPUTS_FOLDER,
    OUTPUTS_FOLDER,
    DATA_FOLDER,
    BANKS,
    STATEMENTS_TYPES,
    MONTH_PATTERNS_ENG,
    MONTH_PATTERNS_SPA,
    NUMERIC_MONTH_PATTERNS
)

__all__ = [
    'PROJECT_ROOT', 
    'DOCUMENTS_FOLDER', 
    'INPUTS_FOLDER', 
    'OUTPUTS_FOLDER', 
    'DATA_FOLDER',
    'BANKS', 
    'STATEMENTS_TYPES',
    'MONTH_PATTERNS_ENG',
    'MONTH_PATTERNS_SPA',
    'NUMERIC_MONTH_PATTERNS'
    ]
