import os

# Root folder of the project
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Paths for documents
DOCUMENTS_FOLDER = os.path.join(PROJECT_ROOT, 'documents')
INPUTS_FOLDER = os.path.join(DOCUMENTS_FOLDER, 'inputs')
OUTPUTS_FOLDER = os.path.join(DOCUMENTS_FOLDER, 'outputs')
DATA_FOLDER = os.path.join(PROJECT_ROOT, 'data')

# Other config variables
BANKS = ['amex', 'banorte', 'bbva', 'citibanamex', 'hsbc', 'inbursa', 'nu', 'santander']

BANKS_CODES = {
    '002': 'citibanamex',
    '006': 'bancomext',
    '009': 'banobras',
    '012': 'bbva',
    '014': 'santander',
    '019': 'banjercito',
    '021': 'hsbc',
    '030': 'bajio',
    '032': 'ixe',
    '036': 'inbursa',
    '037': 'interacciones',
    '042': 'mifel',
    '044': 'scotiabank',
    '058': 'banregio',
    '059': 'invex',
    '060': 'bansi',
    '062': 'afirme',
    '072': 'banorte',
    '102': 'the royal bank',
    '103': 'amex',
    '106': 'bamsa',
    '108': 'tokyo',
    '110': 'jp morgan',
    '112': 'bmonex',
    '113': 've por mas',
    '116': 'ing',
    '124': 'deutsche',
    '126': 'credit suisse',
    '127': 'azteca',
    '128': 'autofin',
    '129': 'barclays',
    '130': 'compartamos',
    '131': 'banco famsa',
    '132': 'bmultiva',
    '133': 'actinver',
    '134': 'wal-mart',
    '135': 'nafin',
    '136': 'interbanco',
    '137': 'bancoppel',
    '138': 'abc capital',
    '139': 'ubs bank',
    '140': 'consubanco',
    '141': 'volkswagen',
    '143': 'cibanco',
    '145': 'bbase',
    '166': 'bansefi',
    '168': 'hipotecaria federal',
    '600': 'monexcb',
    '601': 'gbm',
    '602': 'masari',
    '605': 'value',
    '606': 'estructuradores',
    '607': 'tiber',
    '608': 'vector',
    '610': 'b&b',
    '614': 'accival',
    '615': 'merrill lynch',
    '616': 'finamex',
    '617': 'valmex',
    '618': 'unica',
    '619': 'mapfre',
    '620': 'profuturo',
    '621': 'cb actinver',
    '622': 'oactin',
    '623': 'skandia',
    '626': 'cbdeutsche',
    '627': 'zurich',
    '628': 'zurichvi',
    '629': 'su casita',
    '630': 'cb intercam',
    '631': 'ci bolsa',
    '632': 'bulltick cb',
    '633': 'sterling',
    '634': 'fincomun',
    '636': 'hdi seguros',
    '637': 'order',
    '638': 'nu',
    '640': 'cb jpmorgan',
    '642': 'reforma',
    '646': 'stp',
    '647': 'telecomm',
    '648': 'evercore',
    '649': 'skandia',
    '651': 'segmty',
    '652': 'asea',
    '653': 'kuspit',
    '655': 'sofiexpress',
    '656': 'unagra',
    '659': 'opciones empresariales del noroeste',
    '670': 'libertad',
    '901': 'cls',
    '902': 'indeval',
    '999': 'n/a',
}

STATEMENTS_TYPES = ['debit', 'credit']

MONTH_PATTERNS_ENG = {
    'january': 'ENE',
    'february': 'FEB',
    'march': 'MAR',
    'april': 'ABR',
    'may': 'MAY',
    'june': 'JUN',
    'july': 'JUL',
    'august': 'AGO',
    'september': 'SEP',
    'october': 'OCT',
    'november': 'NOV',
    'december': 'DIC'
}

MONTH_PATTERNS_SPA = {
    'Enero': 'ENE',
    'Febrero': 'FEB',
    'Marzo': 'MAR',
    'Abril': 'ABR',
    'Mayo': 'MAY',
    'Junio': 'JUN',
    'Julio': 'JUL',
    'Agosto': 'AGO',
    'Septiembre': 'SEP',
    'Octubre': 'OCT',
    'Noviembre': 'NOV',
    'Diciembre': 'DIC'
}

NUMERIC_MONTH_PATTERNS = {
    '01': 'ENE',
    '02': 'FEB',
    '03': 'MAR',
    '04': 'ABR',
    '05': 'MAY',
    '06': 'JUN',
    '07': 'JUL',
    '08': 'AGO',
    '09': 'SEP',
    '10': 'OCT',
    '11': 'NOV',
    '12': 'DIC'
}
